ReserveStudent/Controllers/ReservationController.cs
 using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReserveStudent.Models.contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ReserveStudent.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace ReserveStudent.Controllers
{
    public class ReservationController : Controller
    {
        private readonly IReservationRepository _repos;
        private readonly IReservationTypeRepository _ReservationTyperepo;
        private UserManager<IdentityUser> _userManger;

        public ReservationController(IReservationRepository repos , IReservationTypeRepository ReservationTyperepo ,UserManager<IdentityUser> userManager )
        {
            _repos = repos;
            _ReservationTyperepo = ReservationTyperepo;
            _userManger = userManager;
        }
        [Authorize(Roles = "Admin")]
    // GET: ReservationController
    public ActionResult Index()
        {
            var today = DateTime.Today;
            var reservations = _repos.GetAll().OrderBy(x=>x.RequestingStudent.Count).Where(x => x.Date == today);
            return View(reservations);
            

        }
        [Authorize(Roles = "Admin")]
        // GET: ReservationController/Details/5
        public ActionResult Review(int id)
        {
            var reservation = _repos.GetById(id);
            var model = new Reservation
            {
                Id = reservation.Id,
                RequestingStudent = reservation.RequestingStudent,
                RequestingStudentId = reservation.RequestingStudentId,
                ReservationType = reservation.ReservationType,
                Date = reservation.Date,
                ReservationTypeId = reservation.ReservationTypeId,
                Status = reservation.Status
            };
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        public ActionResult ApprouveRequest(int id)
        {
            try
            {
                var user = _userManger.GetUserAsync(User).Result;
                var reservation = _repos.GetById(id);
                reservation.Status = true;
                reservation.RequestingStudent.Count += 1;
                _repos.Update(reservation);
                return RedirectToAction("Index");

            }
            catch (Exception)
            {

                return RedirectToAction("Index");
            }
        }
        [Authorize(Roles = "Admin")]
        public ActionResult RejectRequest(int id)
        {
            try
            {
                var user = _userManger.GetUserAsync(User).Result;
                var reservation = _repos.GetById(id);
                reservation.Status = false;
                _repos.Update(reservation);
                return RedirectToAction("Index");

            }
            catch (Exception )
            {

                return RedirectToAction("Index");
            }
        }


        // GET: ReservationController/Create
        public ActionResult Create()
        {
            var reservationTypes = _ReservationTyperepo.GetAll();
             var resrvTypesItems = reservationTypes.Select(x => new SelectListItem
            {
                Text = x.NameType,
                Value = x.Id.ToString()
            }).ToList();
            var model = new CreateReservationViewModel
            {
               ReservationTypes = resrvTypesItems
            };
            return View(model);


           
        }

        // POST: ReservationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateReservationViewModel model)
        {
            try
            {
                var Date = Convert.ToDateTime(model.Date);

                var reservationTypes = _ReservationTyperepo.GetAll().ToList();
                var reservationTypesItems = reservationTypes.Select(x => new SelectListItem
                {
                    Text = x.NameType,
                    Value = x.Id.ToString()
                }).ToList();
                model.ReservationTypes = reservationTypesItems;
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                var student = _userManger.GetUserAsync(User).Result;


                var reservation = new Reservation
                {
                    RequestingStudentId = student.Id,
                    Date = Date,
                    Status = null,
                    ReservationTypeId = model.ReservationTypeId

                };
              
                var isSuccuss = _repos.Create(reservation);
                if (!isSuccuss)
                {
                    ModelState.AddModelError("", "Something went wrong in the submit action");
                    return View(model);
                }
                return RedirectToAction(nameof(StudentReservations));
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: ReservationController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ReservationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReservationController/Delete/5
        public ActionResult Delete(int id)
        {
            var reservation = _repos.GetById(id);
            var isSuccuss = _repos.Delete(reservation);
            if (!isSuccuss)
            {

                return View();
            }
            return RedirectToAction(nameof(StudentReservations));
        }

        // POST: ReservationController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        public ActionResult StudentReservations()
        {
            var user = _userManger.GetUserAsync(User).Result;

            var Reservations = _repos.GetReservationsByStudent(user.Id);

            return View(Reservations);
        }
    }
}

ReserveStudent/Controllers/ReservationTypeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ReserveStudent.Models.contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ReserveStudent.Models;

namespace ReserveStudent.Controllers
{
    public class ReservationTypeController : Controller
    {
        private readonly IReservationTypeRepository _repo;
        public ReservationTypeController(IReservationTypeRepository repo)
        {
            _repo = repo;
        }

        // GET: ReservationType
        public ActionResult Index()
        {
            var reservationTypes = _repo.GetAll();
            return View(reservationTypes);
        }

        // GET: ReservationType/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ReservationType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReservationType/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ReservationType reservation)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(reservation);
                }

                var reservationType = new ReservationType
                {
                    Id = reservation.Id,
                    NameType = reservation.NameType,
                    AccessNumber = reservation.AccessNumber
                };

                var isSuccess = _repo.Create(reservationType);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong");
                    return View(reservation);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ReservationType/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_repo.IsExist(id))
            {
                return NotFound();
            }
            var AbsenceType = _repo.GetById(id);
            var model = new ReservationType
            {
                Id = AbsenceType.Id,
                NameType = AbsenceType.NameType,
                AccessNumber = AbsenceType.AccessNumber
            };
            return View(model);
        }

        // POST: ReservationType/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ReservationType model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", "Something went wrong");
                    return View(model);
                }
                var ReservationType = new ReservationType
                {
                    Id = model.Id,
                    NameType = model.NameType,
                    AccessNumber = model.AccessNumber
                };
                var isSuccess = _repo.Update(ReservationType);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something went wrong");
                    return View(model);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something went wrong");
                return View();
            }
        }

        // GET: ReservationType/Delete/5
        public ActionResult Delete(int id)
        {
            var reservationType = _repo.GetById(id);
            if (reservationType == null)
            {
                return NotFound();
            }
            var IsSuccess = _repo.Delete(reservationType);
            if (!IsSuccess)
            {
                return BadRequest();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: ReservationType/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                var reservationType = _repo.GetById(id);
                if (reservationType == null)
                {
                    return NotFound();
                }
                var IsSuccess = _repo.Delete(reservationType);
                if (!IsSuccess)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ReserveStudent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReserveStudent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReserveStudent</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-controller="Administration" asp-action="ListRoles">List Roles</a>
            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="index">Resevation</a>
                            </li>
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="ReservationType" asp-action="index">reservation type </a>
                                            </li> }
                                                        else
                                                        {
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="reservation" asp-action="StudentReservations"> my Resevation</a>
                                            </li>}
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ReserveStudent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>